name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - dask
  - xarray
  - flake8
  - cupy
  - cudatoolkit
  - pint=0.8.1
